#all_resources:
#  show: if logged_in
#  edit: if may_show
#  delete: if may_edit
#
#welcome:
#  show: if logged_in
#  register: unless logged_in
#
#picture:
#  show: if owner or friend
#
#user_content:
#  applies_to: picture, comment
#  create: if logged_in
#  edit: if owner